[package]
name = "basalt_serde"
version = "0.1.0"
authors = ["Nicholas McDaniel <nickmcdaniel00@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
